# Generated by Django 5.2.5 on 2026-04-16 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=5000)),
                ('adress', models.CharField(blank=True, max_length=400)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfil',
                'verbose_name_plural': 'UserProfils',
            },
        ),
        migrations.DeleteModel(
            name='Usermodels',
        ),
    ]
